.\" -*- nroff -*-
.TH NEOIP-WEBPEER 8 "Dec 2006" "neoip-webpeer(1)" "neoip-webpeer's Manual"
.SH NAME
neoip-webpeer - all the neoip application related to the web
.SH SYNOPSIS
.B neoip-webpeer
[--config_dir dirname] [--help] [--version]
.SH DESCRIPTION
neoip-webpeer is a deamon which bundble all the neoip application related to 
the web i.e. neoip-casti, neoip-casto and neoip-oload

.SH OPTIONS
.TP
.I "-c, --config_dir dirname"
set the configuration directory.
If not specified, it uses /etc/neoip-webpeer.
.TP
.I "-h, --help"
display the inlined help
.TP
.I "-v, --version"
display the version string

  
.SH FILES
\fI/etc/neoip-webpeer\fR
default configuration directory

.SH LICENSE
The license is proprietary and this programm should be used for testing purpose only

.SH AUTHOR
.B neoip-webpeer
has been written by Jerome Etienne <jme@off.net>

NeoIP's homepage is http://off.net/~jme/neoip

.SH BUGS
If you find bugs, email me.
Note that the metalink support is experimental.
