/*! \file
    \brief Header of the \ref kad_pkttype_t

*/


#ifndef __NEOIP_KAD_PKTTYPE_HPP__ 
#define __NEOIP_KAD_PKTTYPE_HPP__ 

/* system include */
/* local include */
#include "neoip_pkttype.hpp"
#include "neoip_namespace.hpp"

NEOIP_NAMESPACE_BEGIN;

NEOIP_PKTTYPE_DECLARATION_START(kad_pkttype_t);
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, PING_REQUEST)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, PING_REPLY)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, STORE_REQUEST)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, STORE_REPLY)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, FINDNODE_REQUEST)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, FINDNODE_REPLY)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, FINDSOMEVAL_REQUEST)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, FINDSOMEVAL_REPLY)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, FINDALLVAL_REQUEST)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, FINDALLVAL_REPLY)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, DELETE_REQUEST)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, DELETE_REPLY)
NEOIP_PKTTYPE_DECLARATION_ITEM(kad_pkttype_t	, RESET_REPLY)
NEOIP_PKTTYPE_DECLARATION_END(kad_pkttype_t);


NEOIP_NAMESPACE_END

#endif	/* __NEOIP_KAD_PKTTYPE_HPP__  */





