/*! \file
    \brief Header of the \ref kad_pkttype_t

*/

/* system include */
/* local include */
#include "neoip_kad_pkttype.hpp"
#include "neoip_assert.hpp"

NEOIP_NAMESPACE_BEGIN;

NEOIP_PKTTYPE_DEFINITION_START(kad_pkttype_t);
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, PING_REQUEST)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, PING_REPLY)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, STORE_REQUEST)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, STORE_REPLY)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, FINDNODE_REQUEST)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, FINDNODE_REPLY)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, FINDSOMEVAL_REQUEST)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, FINDSOMEVAL_REPLY)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, FINDALLVAL_REQUEST)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, FINDALLVAL_REPLY)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, DELETE_REQUEST)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, DELETE_REPLY)
NEOIP_PKTTYPE_DEFINITION_ITEM(kad_pkttype_t	, RESET_REPLY)
NEOIP_PKTTYPE_DEFINITION_END(kad_pkttype_t);

NEOIP_NAMESPACE_END

