.TH NEOIP_FILEFORMAT_TRACKGEN_SPACE_YOUPORN 8 "Dec 2006" "trackgen_space_youporn file format(1)" "trackgen_space_youporn file format's Manual"
.SH NAME
neoip trackgen_space_youporn format extension
.SH DESCRIPTION
trackgen_space_youporn is a source of track. It relies on the http://youporn.com
website to generate the track list. Currently it has no criteria to choose
the track and only pick them at random. NOTE: this may change in the future.

.SH EXAMPLES
non-applicable

.SH AUTHOR
.B neoip-playlist-
has been written by Jerome Etienne <jme@off.net>

NeoIP homepage is http://off.net/~jme/neoip

.SH BUGS
If you find bugs, email me.
