.\" -*- nroff -*-
.TH NEOIP-OLOAD 8 "Dec 2006" "neoip-oload(1)" "neoip-oload's Manual"
.SH NAME
neoip-oload - http gateway to download file http/bittorrent/metalink
.SH SYNOPSIS
.B neoip-oload
[--config_dir dirname] [--help] [--version]
.SH DESCRIPTION
neoip-oload is a deamon which allow to read files over the internet.
Those files may be static http content, .torrent content or .metalink content.

TODO this man page is just a stub. complete it

.SH OPTIONS
.TP
.I "-c, --config_dir dirname"
set the configuration directory.
If not specified, it uses /etc/neoip-oload.
.TP
.I "-h, --help"
display the inlined help
.TP
.I "-v, --version"
display the version string

.SH FILES
\fI/etc/neoip-oload\fR
default configuration directory

.SH LICENSE
The license is proprietary and this programm should be used for testing purpose only

.SH AUTHOR
.B neoip-oload
has been written by Jerome Etienne <jme@off.net>

NeoIP's homepage is http://off.net/~jme/neoip

.SH BUGS
If you find bugs, email me.
Note that the metalink support is experimental.
