.TH NEOIP_FILEFORMAT_TRACKGEN_SPACE_YOUTUBE 8 "Dec 2006" "trackgen_space_youtube file format(1)" "trackgen_space_youtube file format's Manual"
.SH NAME
neoip trackgen_space_youtube format extension
.SH DESCRIPTION
trackgen_space_youtube is a source of track.
It relies on the http://youtube.com website to generate the track list.
The "space" description in "desc" field is an object containing various
fields directly mapped to the youtube.rb API, which in turn is a mapping
of the youtube.com webAPI.


.SH EXAMPLES
{	"cmd"	=> "videos_by_user",
	"arg"	=> {	"user"	=> "seeso"
			}
}

.SH AUTHOR
.B neoip-playlist-
has been written by Jerome Etienne <jme@off.net>

NeoIP homepage is http://off.net/~jme/neoip

.SH BUGS
If you find bugs, email me.
