# This is a makefile on top of the neoip-pkger.rb
#
# - TODO it is mostly a stub right 
# - but it has "make clean"
# - TODO to doc too

all:
	./neoip_pkger.rb epm_install neoip-webpack full
	
win32:
	./neoip_pkger.rb nsis_install neoip-webpack full

clean:
	./neoip_pkger.rb all all clean
