/*! \file
    \brief Definition of the \ref scnx_err_t

*/

/* system include */
/* local include */
#include "neoip_scnx_err.hpp"
#include "neoip_namespace.hpp"

NEOIP_NAMESPACE_BEGIN

NEOIP_ERRTYPE_DEFINITION_START(scnx_err_t)
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, OK			, "OK")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, ERROR			, "ERROR")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, BOGUS_PKT		, "BOGUS_PKT")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, BAD_NONCE		, "BAD_NONCE")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, BAD_COOKIE		, "BAD_COOKIE")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, ACL_REFUSED		, "ACL_REFUSED")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, BAD_SIGNATURE		, "BAD_SIGNATURE")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, BAD_POP		, "BAD_POP")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, BAD_ITOR_STATE	, "BAD_ITOR_STATE")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, BAD_AUXNEGO		, "BAD_AUXNEGO" )
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, CIPH_NEGO_FAILED	, "CIPH_NEGO_FAILED")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, AUTH_NEGO_FAILED	, "AUTH_NEGO_FAILED")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, BAD_FULL_CIPH		, "BAD_FULL_CIPH")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, BAD_FULL_AUTH		, "BAD_FULL_AUTH")
NEOIP_ERRTYPE_DEFINITION_ITEM(scnx_err_t	, REPLAYED_PKT		, "REPLAYED_PKT")
NEOIP_ERRTYPE_DEFINITION_END(scnx_err_t)

NEOIP_NAMESPACE_END





